from rv_reporter.rendering.html_renderer import render_html


def test_network_renderer_handles_missing_metrics_payload() -> None:
    report = {
        "report_type_id": "network_queue_congestion",
        "report_title": "Network Queue Congestion Report",
        "summary": "Generated by model",
        "sections": [],
        "alerts": [],
        "recommendations": [],
        "tables": [],
        "charts": [],
        "metadata": {"schema_version": "1.0.0"},
    }
    html = render_html(report)
    assert "Queue Summary" in html
    assert "Overall Drop Ratio (Bytes)" in html


def test_pm_renderer_handles_missing_metrics_payload() -> None:
    report = {
        "report_type_id": "pm_export_health",
        "report_title": "PM Export Health Report",
        "summary": "Generated by model",
        "sections": [],
        "alerts": [],
        "recommendations": [],
        "tables": [],
        "charts": [],
        "metadata": {"schema_version": "1.0.0"},
    }
    html = render_html(report)
    assert "PM Export Summary" in html
    assert "PM Health Charts" in html


def test_renderer_auto_formats_long_section_into_list() -> None:
    report = {
        "report_type_id": "custom_type",
        "report_title": "Custom",
        "summary": "x",
        "sections": [
            {
                "title": "Analysis",
                "body": (
                    "First finding is significant and impacts traffic quality. "
                    "Second finding indicates sustained pressure under load. "
                    "Third finding suggests policy tuning is required."
                ),
            }
        ],
        "alerts": [],
        "recommendations": [],
        "tables": [],
        "charts": [],
        "metadata": {},
    }
    html = render_html(report)
    assert "<ul>" in html
    assert "<li>" in html
