from rv_reporter.rendering.html_renderer import render_html


def test_network_renderer_handles_missing_metrics_payload() -> None:
    report = {
        "report_type_id": "network_queue_congestion",
        "report_title": "Network Queue Congestion Report",
        "summary": "Generated by model",
        "sections": [],
        "alerts": [],
        "recommendations": [],
        "tables": [],
        "charts": [],
        "metadata": {"schema_version": "1.0.0"},
    }
    html = render_html(report)
    assert "Queue Summary" in html
    assert "Overall Drop Ratio (Bytes)" in html


def test_pm_renderer_handles_missing_metrics_payload() -> None:
    report = {
        "report_type_id": "pm_export_health",
        "report_title": "PM Export Health Report",
        "summary": "Generated by model",
        "sections": [],
        "alerts": [],
        "recommendations": [],
        "tables": [],
        "charts": [],
        "metadata": {"schema_version": "1.0.0"},
    }
    html = render_html(report)
    assert "PM Export Summary" in html
    assert "PM Health Charts" in html


def test_renderer_auto_formats_long_section_into_list() -> None:
    report = {
        "report_type_id": "custom_type",
        "report_title": "Custom",
        "summary": "x",
        "sections": [
            {
                "title": "Analysis",
                "body": (
                    "First finding is significant and impacts traffic quality. "
                    "Second finding indicates sustained pressure under load. "
                    "Third finding suggests policy tuning is required."
                ),
            }
        ],
        "alerts": [],
        "recommendations": [],
        "tables": [],
        "charts": [],
        "metadata": {},
    }
    html = render_html(report)
    assert "<ul>" in html
    assert "<li>" in html


def test_wireshark_renderer_renders_ptp_focus_when_payload_present() -> None:
    report = {
        "report_type_id": "wireshark_capture_health",
        "report_title": "Wireshark Capture Health Report",
        "summary": "Generated by model",
        "sections": [],
        "alerts": [],
        "recommendations": [],
        "tables": [
            {
                "name": "metrics_payload",
                "rows": [
                    {
                        "summary": {
                            "packets": 100,
                            "total_bytes": 10000,
                            "unique_src_ips": 2,
                            "unique_dst_ips": 2,
                            "avg_packet_size_bytes": 100.0,
                            "tcp_syn_packets": 0,
                            "tcp_rst_packets": 0,
                            "dns_query_packets": 0,
                            "ptp_packets": 60,
                            "ptp_share_pct": 60.0,
                            "ptp_g8275_1_likely": True,
                        },
                        "protocol_breakdown": [],
                        "top_talkers": [],
                        "top_conversations": [],
                        "time_trend": [],
                        "ptp_summary": {
                            "packets": 60,
                            "g8275_1_likely": True,
                            "sync_packets": 20,
                            "follow_up_packets": 19,
                            "announce_packets": 10,
                            "event_port_packets": 30,
                            "general_port_packets": 30,
                            "correction_ns_median": 10.0,
                            "correction_ns_p95": 25.0,
                            "timestamp_delta_ns_median": 150.0,
                        },
                        "ptp_message_mix": [{"message_type": "Sync", "packets": 20, "pct": 33.3}],
                        "ptp_message_time_trend": [
                            {
                                "time_utc": "2026-02-09 11:52:00+00:00",
                                "ptp_packets": 120,
                                "sync_packets": 80,
                                "follow_up_packets": 0,
                                "announce_packets": 40,
                                "correction_ns_median": 10000.0,
                                "correction_ns_p95": 10400.0,
                            }
                        ],
                        "ptp_port_health": [
                            {
                                "sender": "00:11:22:33:44:55:66:04",
                                "port_number": 4,
                                "packets": 30,
                                "sync_packets": 10,
                                "follow_up_packets": 10,
                                "announce_packets": 5,
                                "sync_interval_ms_median": 125.0,
                                "sync_interval_ms_p95": 130.0,
                                "correction_ns_median": 9.0,
                                "correction_ns_p95": 12.0,
                            }
                        ],
                        "ptp_timing": [],
                        "ptp_source_comparison": [
                            {
                                "source_file": "port3.pcapng",
                                "packets": 100,
                                "sync_packets": 60,
                                "follow_up_packets": 0,
                                "announce_packets": 40,
                                "two_step_pct": 0.0,
                                "correction_ns_median": 10300.0,
                                "correction_ns_p95": 10500.0,
                                "timestamp_delta_ns_median": -100.0,
                            }
                        ],
                        "ptp_time_sync_logic": {
                            "focus_scope": "g8275_1_domain24",
                            "focus_packets": 60,
                            "ptp_mode_inferred": "one_step_or_follow_up_not_captured",
                            "lock_score": 62,
                            "lock_likelihood": "medium",
                            "lock_reasons": ["Sync cadence is stable.", "Large frame-to-origin timestamp offset observed."],
                        },
                        "ptp_state_flow": [
                            {
                                "time_utc": "2026-02-09 11:52:00+00:00",
                                "state": "warning",
                                "state_score": 58,
                                "ptp_packets": 120,
                                "sync_packets": 80,
                                "follow_up_packets": 0,
                                "announce_packets": 40,
                                "correction_ns_median": 10000.0,
                                "correction_ns_p95": 10400.0,
                                "timestamp_delta_ns_median": -35000000000.0,
                                "reason": "Large frame/origin timestamp offset.",
                            }
                        ],
                    }
                ],
            }
        ],
        "charts": [],
        "metadata": {"schema_version": "1.0.0"},
    }
    html = render_html(report)
    assert "PTPv2 (1588) Focus" in html
    assert "PTP Sender / Port Health" in html
    assert "PTP Source Comparison" in html
    assert "PTP Time-Sync Messages Over Time" in html
    assert "PTP Message Types Over Time" in html
    assert "PTP Time-Sync Logic" in html
    assert "PTP State Flow Over Time" in html
    assert "PTP State Score Over Time" in html
